### PR TITLE
Add useWSL to settings

### PR DESCRIPTION
**Pull request by jchavarri**
Companion of https://github.com/reasonml-editor/vscode-reasonml/pull/114.

Adds:
- An option `useWSL` (bool) to settings
- Transform file uris parsed by `bsb` when `useWSL` is `true`, so they are Windows friendly
- Uses `bash.exe` as command for all processes if  `useWSL` is `true`.

@freebroccolo l will probably ask @superherointj to test this locally, but it's ready for review.

### CODE REVIEW

**Comment by freebroccolo** [comment]
Thanks for this!

I had started writing up some items for integrating WSL support into the server in a new issue at https://github.com/freebroccolo/ocaml-language-server/issues/45

I also just briefly tried this on my windows system with OCaml 4.05.0 and merlin installed via WSL but it doesn't seem to be working and I haven't had a chance to dig deeper yet. It looks like it is probably failing to establish the initial communication with merlin for some reason.

**Comment by superherointj** [comment]
Only Merlin 2.5 is working. There were changes in Merlin 3.

**Comment by freebroccolo** [comment]
> Only Merlin 2.5 is working. There were changes in Merlin 3.

As far as I'm aware, Merlin 3 should be working with the server normally. Is the problem specific to WSL?

**Comment by superherointj** [comment]
I don't know the why but I could only get it to work when I downgraded to 2.5. And upgrading to 3.0.3 would lead to odd behaviors like freezing the editing of text on editor (any file) on random times. Idk why that happened. But downgrading made everything fine again... There is something weird to it.

**Comment by freebroccolo** [comment]
Interesting. I will try that. When I looked at Merlin 3 earlier, they did implement a new way to communicate with it (running in 1-shot mode instead of as a long running process) but it is by default supposed to still be backward compatible. At least it has been working that way for me on macOS and Linux up to this point.

**Comment by superherointj** [comment]
Can you analise this patch with Merlin 2.5, so we can have it asap? Because it actually fixes problems on Windows. (the path translation)

**Comment by freebroccolo** [comment]
Okay, I was able to get this partially working with OCaml 4.02.3 and Merlin 2.5.5. The issue before is that I was using `yarn link` under WSL. I guess this was creating a symlink that Windows didn't understand when it tried to launch the server from outside of WSL (due to the `/mnt/` prefixing).

So, it seems to partially work now in that the server successfully starts and seems to be communicating with `ocamlmerlin`. Hover and diagnostics appear to work, but jump-to-definition is not working still due to file path translation issues. The codelens type signatures also do not seem to be working, probably for the same reason.

I am willing to get this merged before everything is in shape like I was thinking of in #45 but I think it still needs a little more work just to get the basic features supported still.

**Comment by superherointj** [comment]
Codelens is working here. It should be working.

**Comment by jchavarri** [comment]
I "simulated" the `wslMode` to make sure the paths resolved properly for `bsb`, but not on a Windows environment, as I unfortunately don't have access to a Windows machine.

@freebroccolo Could you confirm if `bsb` diagnostics are pointing to the right files/lines in your computer when loading this branch, please?

One thing that makes sense to me from what @freebroccolo is mentioning is that as far as I know, merlin running on WSL should return Linux uris, not Windows uris. So I'm guessing that somehow, the env @superherointj is using to test is not using merlin on WSL but rather the native Windows version (??)

@superherointj Unfortunately, I can't spend more time on this. Also, not having a Windows machine around makes it very hard (or rather, impossible) to test what things work or what doesn't. And remote access is not a proper way of working. I understand you want this patch merged asap, but in that case I encourage you to test this branch locally, reuse it if you want, or even build on top of this PR any missing features that it might be lacking. I agree with @freebroccolo that it'd be good to have everything working before shipping it.

**Comment by freebroccolo** [comment]
> @freebroccolo Could you confirm if bsb diagnostics are pointing to the right files/lines in your computer when loading this branch, please?

I will check that.

> One thing that makes sense to me from what @freebroccolo is mentioning is that as far as I know, merlin running on WSL should return Linux uris, not Windows uris. So I'm guessing that somehow, the env @superherointj is using to test is not using merlin on WSL but rather the native Windows version (??)

Yes, that's right that merlin under WSL will be returning Linux URIs. I'm not sure yet why the rest of the features weren't really working but I am pretty sure that we're going to have to map out all the places were files are referenced in communication on both sides of the connection and ensure that they are translated back and forth properly. Even if most of the stuff should work now, we'll have to be pretty thorough about keeping on top of that in the future as more features get added.

> @superherointj Unfortunately, I can't spend more time on this. Also, not having a Windows machine around makes it very hard (or rather, impossible) to test what things work and what things don't.

I have access to a windows machine (one of my main workstations) and should have some time over the next few days that I can spend on this. Now that I have a pretty good idea of what's needed to make the server work with WSL, I think I can probably finish this up without any major issues.

Like I said earlier, I've wanted to have this for awhile too so I'll make sure we get it in a release soon.

**Comment by superherointj** [comment]
I was testing on WSL for sure; There isn't `ocamlmerlin` on PATH. See:
```
D:\dev\project1>ocamlmerlin -version
'ocamlmerlin' is not recognized as an internal or external command, operable program or batch file.
```
I was having trouble testing the patch because I couldn't link up the dependency on Windows without triggering lifecycle script errors, not Windows compatible.

**Pull request closed without merging**
