### PR TITLE
Integrate better errors

### PR DESCRIPTION
**Pull request by jchavarri**
⚠️  WIP ⚠️ 

Targets #17.

### TODO

~~- [ ] Make it work also on edit (not only save)~~ Edit: Deferred, can't see an easy way to do so, unless there's some way to plug the edited file input to `bsb`?
~~- [ ] Create PR to allow ninja to print colors upstream (BuckleScript)~~ Edit: not needed after adding explicit output
- [x] Multiple files
- [x] Line numbers? (https://github.com/BuckleScript/bucklescript/issues/2015)
- [x] Match file paths from bsb output to the current vscode document
- [x] Send empty diagnostics array for files after being fixed
- [ ] Multiple errors per file (is it possible?)
- [x] Check for `bsconfig.json`? Edit: read bsb path from settings

### Bugs:
~~- [ ] Error with no lines:~~ Covered in https://github.com/freebroccolo/ocaml-language-server/issues/34
```
while (current <: !(length input)) {
};
```
~~- [ ] Fatal error not parsed:~~ (can't repro 😕 )
```
BSB check build spec : OK 

Making the dependency world!
Package stack: the-super-tiny-compiler  
ninja.exe -C lib/bs 
ninja: Entering directory `lib/bs'
[1/1] Building src/compiler-TheSuperTinyCompiler.cmj
FAILED: src/compiler-TheSuperTinyCompiler.cmj /Users/javi/Development/github/the-super-tiny-compiler/lib/js/src/compiler.js src/compiler-TheSuperTinyCompiler.cmi 
/Users/javi/.nvm/versions/node/v6.9.4/lib/node_modules/bs-platform/bin/bsc.exe -bs-package-map the-super-tiny-compiler  -bs-package-output commonjs:lib/js/src -bs-assume-no-mli -bs-no-builtin-ppx-ml -bs-no-implicit-include  -I . -I src   -nostdlib -I '/Users/javi/Development/github/the-super-tiny-compiler/node_modules/bs-platform/lib/ocaml' -bs-super-errors -no-alias-deps -color always -w -40+6+7+27+32..39+44+45 -bs-re-error -o src/compiler-TheSuperTinyCompiler.cmj -c  src/compiler.mlast 
Fatal error: exception Failure("File \"syntax/ast_ffi_types.ml\", line 253, characters 13-20compiler version mismatch, please do a clean build")
ninja: build stopped: subcommand failed.
Error: Command failed: /Users/javi/.nvm/versions/node/v6.9.4/lib/node_modules/bs-platform/bin/bsb.exe -make-world
Error happened when running command /Users/javi/.nvm/versions/node/v6.9.4/lib/node_modules/bs-platform/bin/bsb.exe with args [ '-make-world' ]
```

- [x] Badly parsed error (see [gist with repro](https://gist.github.com/jchavarri/06a1874e6940ee73a60b228aca682ee6))
```
        ens initialMachine.state
  444 │ };
  
  You forgot to handle a possible value here, for example: 
([], Some _, _, _) // This is not parsed
```

### CODE REVIEW

**Comment by jchavarri** [comment]
@freebroccolo @chenglou Baby steps:

image

Wrote some todo items in the description that I guess have to be figured out, the list also helps me know what to tackle next.

The most immediate questions I have are:
- How to get line numbers from bsb output? I thought I could somehow get them from the color decoration, but `spawn` seems to remove them
- Do we have to use `bsb` in the first place? Or better `bsc`?
- Is there a way to get more than one error from `bsb`? Or is the strategy "get one error (if any) from bsb, the rest from merlin"?

Thanks!

**Comment by arxanas** [comment]
This looks cool! Do the better errors work for plain OCaml code, and does it have to be specially integrated into the project to work?

**Comment by chenglou** [comment]
They do work in plain ocaml. Here's the blog post: https://reasonml.github.io/community/blog/#way-way-waaaay-nicer-error-messages

@jchavarri they're indeed not written in the output. Which format would you like it to be? I'll expose you a special hook or something.

**Comment by jchavarri** [comment]
> Which format would you like it to be?

@chenglou It could be anything, maybe something like what `bsc` outputs without `bs-super-errors`?

`File "src/a.re", line 1, characters 13-18:`

Wdyt?

**Comment by chenglou** [comment]
Lol, why would you need that if I can expose you the easier format:

```
===File===
sec/a.re
===start line===
1
===end line===
...
===start char===
...
```

**Comment by jchavarri** [comment]
> does it have to be specially integrated into the project to work?

@arxanas the way I was thinking to trigger it is to check for `bsconfig.json` on the project root, and then try to use `bsb` from `node_modules`, or fall back to the global command in case it's not found there.

**Comment by jchavarri** [comment]
> - [ ] Make it work also on edit (not only save)

I've been looking for ways to send the edited file live data to `bsb`, but I'm not sure if that's possible. My idea was to only use `bsb` to get the diagnostics. But if there's no way to do this, it would mean the analyzer would pull the diagnostics from `merlin` when editing ([`onDidChangeTextDocument`](https://github.com/jchavarri/ocaml-language-server/blob/890fd65d46f8e89b6a2ca74e35cb404e2ba46072/src/server/session/synchronizer.ts#L37-L49)), and from `bsb` when saving ([`onDidSaveTextDocument`](https://github.com/jchavarri/ocaml-language-server/blob/890fd65d46f8e89b6a2ca74e35cb404e2ba46072/src/server/session/synchronizer.ts#L51-L55)). Not sure if this is ideal, as users would be seeing different messages before and after saving.

> bsb uses ninja (check ninja --help or bsb -- --hep. There's a flag called -k bla which tells the build system to keep going even after getting a build error bla times.

@chenglou Neither `bsc` nor `bsb` expose `-k`. I tested running `ninja` and passed `-k 9999` (tried `-k 0` too), but it still fails after encountering the first error, any ideas why? (I tried multiple errors in single file or in multiple files).

```
ninja: error: rebuilding 'build.ninja': cannot make progress due to previous errors
```

**Comment by freebroccolo** [comment]
> I've been looking for ways to send the edited file live data to bsb, but I'm not sure if that's possible. My idea was to only use bsb to get the diagnostics (if a bsconfig was found). But if there's no way to do this, it would mean the analyzer would pull the diagnostics from merlin when editing (onDidChangeTextDocument), and from bsb when saving (onDidSaveTextDocument). Not sure if this is ideal, as users would be seeing different messages before and after saving.

Yeah, this is something I was a little worried about actually…

In principle, the better errors functionality doesn't need to be tied to the BuckleScript tooling though, does it? That's where the need to gather this information on save comes from, right?

If it's critical that this uses `bsb` one option would be to try and have some sort of save timer. I do something similar in another extension [here](https://github.com/freebroccolo/vscode-redprl). That one is not using a language server but I think it would be possible to adapt it. That approach is kind of messy though and could potentially cause problems with other interactive features.

**Comment by chenglou** [comment]
It's currently tied to BuckleScript because we needed a few tweaks in the compiler; the ocaml plugin system wasn't enough for that. Hopefully the (mostly agnostic) tweaks get upstreamed one day and then we can get this super-errors functionality as a plugin and remove the hard-coded integration here.

**Comment by freebroccolo** [comment]
> But if there's no way to do this, it would mean the analyzer would pull the diagnostics from merlin when editing (onDidChangeTextDocument), and from bsb when saving (onDidSaveTextDocument). Not sure if this is ideal, as users would be seeing different messages before and after saving.

This might not be as bad as it sounds actually. We wouldn't have to get rid of the merlin diagnostics but just show them together with the diagnostics from `bsb`–when they are available. I think we could prioritize the order in which they are shown too so that the `bsb` diagnostics are listed first.

I think it would be better to do it this way than sometimes showing one and sometimes showing another or requiring the user to configure a setting to choose which ones to show.

**Comment by chenglou** [comment]
I think that works. Except merlin has false-positives, which this system prevents.

Also merlin can't actually tell you which un-opened file is erroring. Running bsb til the end tells you _all_ the errors. A real-life problem is when some other files' errors are resolved when you save your current one, but merlin doesn't show that. Theoretically you can query _all_ the open files and closed files every time, but that's not ideal.

**Comment by freebroccolo** [comment]
If it's worth it, I suppose we could prune the merlin diagnostics based on the `bsb` output when it's actually possible to do that. But I think it's probably enough to just mention somewhere in documentation or whatever that the merlin diagnostics may not always be completely accurate for various reasons.

**Comment by jchavarri** [comment]
@freebroccolo @chenglou Thanks for the pointers! 👍 

I spent some time today trying to read ansi color codes from the spawned `bsb` process output with no luck. No matter what I try (pipes, encoding, `--color` flag...) the only string that gets the ansi code wrapper is `Building`:

image

image

Those 3 parts at the bottom have different colors on the regular output.

To make things more confusing, this happens on the debugging console that is attached to the running process. But on the "Extension Dev Host" (that prints to the Output tab, not Debug Console) there's no colors at all:

image

We could maybe try with other [non printable chars](http://web.itu.edu.tr/sgunduz/courses/mikroisl/ascii.html) or go with the format that @chenglou posted above (or st similar).

**Comment by jchavarri** [comment]
Found something that would explain the second problem (no colors on "Output" panel): colors are not supported there apparently: https://github.com/Microsoft/vscode/issues/571).

About the first issue (ANSI chars missing on `bsb` output) I was able to discard it's a vscode or node problem by running `bsb > file.txt`, which generates this file:

```
[1;33mBSB check[0m build spec : OK 
ninja.exe -C lib/bs 
ninja: Entering directory `lib/bs'
[1/2] [34mBuilding[39m [2msrc/a.cmj[22m
FAILED: src/a.cmj /Users/javi/Development/sandbox/reason-hello/lib/js/src/a.js src/a.cmi 
/Users/javi/.nvm/versions/node/v6.9.4/lib/node_modules/bs-platform/bin/bsc.exe -bs-package-name reason-hello  -bs-package-output commonjs:lib/js/src -bs-assume-no-mli -bs-no-builtin-ppx-ml -bs-no-implicit-include  -I src   -nostdlib -I '/Users/javi/Development/sandbox/reason-hello/node_modules/bs-platform/lib/ocaml' -bs-super-errors -no-alias-deps -color always -w -40+6+7+27+32..39+44+45 -bs-re-error -o src/a.cmj -c  src/a.mlast 

  We've found a bug for you!
  /Users/javi/Development/sandbox/reason-hello/src/a.re
  
  1 │ let a: int = 2;
  2 │ 
  3 │ let a: int = "rer";
  4 │ 
  5 │ let a: int = " rer";
  
  This is:
    string
  But somewhere wanted:
    int
```

Or with `bsb | hexdump -C`:

```
00000000  1b 5b 31 3b 33 33 6d 42  53 42 20 63 68 65 63 6b  |.[1;33mBSB check|
00000010  1b 5b 30 6d 20 62 75 69  6c 64 20 73 70 65 63 20  |.[0m build spec |
00000020  3a 20 4f 4b 20 0a 6e 69  6e 6a 61 2e 65 78 65 20  |: OK .ninja.exe |
00000030  2d 43 20 6c 69 62 2f 62  73 20 0a 6e 69 6e 6a 61  |-C lib/bs .ninja|
00000040  3a 20 45 6e 74 65 72 69  6e 67 20 64 69 72 65 63  |: Entering direc|
00000050  74 6f 72 79 20 60 6c 69  62 2f 62 73 27 0a 5b 31  |tory `lib/bs'.[1|
00000060  2f 32 5d 20 1b 5b 33 34  6d 42 75 69 6c 64 69 6e  |/2] .[34mBuildin|
00000070  67 1b 5b 33 39 6d 20 1b  5b 32 6d 73 72 63 2f 61  |g.[39m .[2msrc/a|
00000080  2e 63 6d 6a 1b 5b 32 32  6d 0a 46 41 49 4c 45 44  |.cmj.[22m.FAILED|
00000090  3a 20 73 72 63 2f 61 2e  63 6d 6a 20 2f 55 73 65  |: src/a.cmj /Use|
...
00000290  6c 61 73 74 20 0a 0a 20  20 57 65 27 76 65 20 66  |last ..  We've f|
000002a0  6f 75 6e 64 20 61 20 62  75 67 20 66 6f 72 20 79  |ound a bug for y|
000002b0  6f 75 21 0a 20 20 2f 55  73 65 72 73 2f 6a 61 76  |ou!.  /Users/jav|
000002c0  69 2f 44 65 76 65 6c 6f  70 6d 65 6e 74 2f 73 61  |i/Development/sa|
000002d0  6e 64 62 6f 78 2f 72 65  61 73 6f 6e 2d 68 65 6c  |ndbox/reason-hel|
000002e0  6c 6f 2f 73 72 63 2f 61  2e 72 65 0a 20 20 0a 20  |lo/src/a.re.  . |
000002f0  20 31 20 e2 94 82 20 6c  65 74 20 61 3a 20 69 6e  | 1 ... let a: in|
00000300  74 20 3d 20 32 3b 0a 20  20 32 20 e2 94 82 20 0a  |t = 2;.  2 ... .|
00000310  20 20 33 20 e2 94 82 20  6c 65 74 20 61 3a 20 69  |  3 ... let a: i|
00000320  6e 74 20 3d 20 22 72 65  72 22 3b 0a 20 20 34 20  |nt = "rer";.  4 |
00000330  e2 94 82 20 0a 20 20 35  20 e2 94 82 20 6c 65 74  |... .  5 ... let|
00000340  20 61 3a 20 69 6e 74 20  3d 20 22 20 72 65 72 22  | a: int = " rer"|
00000350  3b 0a 20 20 0a 20 20 54  68 69 73 20 69 73 3a 0a  |;.  .  This is:.|
00000360  20 20 20 20 73 74 72 69  6e 67 0a 20 20 42 75 74  |    string.  But|
00000370  20 73 6f 6d 65 77 68 65  72 65 20 77 61 6e 74 65  | somewhere wante|
00000380  64 3a 0a 20 20 20 20 69  6e 74 0a 20 20 0a 5b 32  |d:.    int.  .[2|
```

@chenglou Given that, do you maybe know if there are different ways in which BuckleScript adds color for each specific parts of the output? Should I open an issue on the BuckleScript repo?

**Comment by jchavarri** [comment]
Oooh could it be [ninja](https://github.com/BuckleScript/bucklescript/blob/e64da96901f0ed1aa3ea900b59860da5eb50a3dd/vendor/ninja/src/build.cc#L140-L159)?

**Comment by jchavarri** [comment]
progress

**Comment by chenglou** [comment]
Sorry didn't see your msgs. How did you get the line numbers here?

**Comment by jchavarri** [comment]
I cloned Bucklescript and updated `ninja.cc` to not strip the ANSI colors. Then took advantage that the line number where the error happens is printed in red, so one part of [the big ass regexp](https://github.com/freebroccolo/ocaml-language-server/pull/32/files#diff-90ce82cc0727a69cf3df8a734a78ab4eR66) is catching that pattern (`\x1b\[[0-9;]*?m(\d*)\x1b\[[0-9;]*?m.*? \│ `).

I know it's hacky, but we can always revisit this :) I will make sure in the next days that this part of the code gets some documentation.

**Comment by bobzhang** [comment]
would some regex pattern be good enough?

**Comment by jchavarri** [comment]
> would some regex pattern be good enough?

@bobzhang You're right. With the current format it's very hard (or impossible) to get the line number without the ANSI colors, as errors can potentially expand through an unknown number of lines, but there's a proposal to add a more explicit output in https://github.com/BuckleScript/bucklescript/pull/2023.

**Comment by jchavarri** [comment]
@freebroccolo I would appreciate a first look. Even if the PR needs https://github.com/BuckleScript/bucklescript/pull/2023 and https://github.com/reasonml-editor/vscode-reasonml/pull/101/files, there are probably things that will need to be polished or that I'm missing.

I solved the integration between merlin and bsb by giving bsb always priority, and falling back to merlin when editing, or when bsb returns no results for the current file.

progress2

**Comment by freebroccolo** [comment]
From a glance it seems pretty reasonable and it appears you've set things up in the code basically how I would expect. Nice job getting this to work!

I will probably have more feedback after I have a chance to test it out myself but in principle I am happy to get this merged once the pieces are in place and all that.

**Comment by chenglou** [comment]
This hybrid model will give us a few benefits. Here are the low-hanging optimizations we can do:

- For errors:
  - If bsb says there are no errors, then it's absolutely right, and we should silence all merlin errors in the same file
  - if bsb says there are errors but merlin shows none, then bsb is still right. Do show them
- For warnings:
  - Unfortunately running a file that has warnings but that successfully compiles means the second time around, the file is simply not touched. So querying all the bsb warnings + errors don't show the files that successfully compiled and had warnings. We might need to do some internal bookkeeping here. I've filed an issue here: https://github.com/BuckleScript/bucklescript/issues/2024

Afaik Merlin made such correctness tradeoff for perf (?). It's possible that in the future, when your repo grows large, such tradeoff starts becoming valuable (e.g. where merlin diagnosis stays fast but bsb slows down. So far even on messenger we haven't encountered this. Bsb is lightning fast). But here we're fine, because one way or another you need to compile your project _anyway_ and if the bsb feedback is slow then merlin will still be there. Though we need to be careful not to show the UI lankily where bsb diagnosis supersede merlin's every few keystrokes.

I'll double check that this is merlin's tradeoff with the maintainer. Even Xcode and Eclipse make such tradeoffs for speed. But since we can afford this hybrid approach that complements each method's shortcomings, for the users we seem magically perfect =)

The long long term plan is to support super-errors as a plugin that merlin can use. Then we can remove these hacks and everyone benefit.

**Comment by jchavarri** [comment]
> If bsb says there are no errors, then it's absolutely right,

@chenglou Relevant: we are not parsing _all_ bsb errors just yet, only the ones that include the lines and character indexes. I'm not aware about all existing possibilities: what other kinds of error output should we handle? afaik there's only this, right?

```
BSB check build spec : OK 

Making the dependency world!
...
File "/Users/javi/Development/sandbox/reason-hello/src/a.re", line 1, characters 8-9:
Error: 1742: Incomplete statement. Did you forget a ";"?


  We've found a bug for you!
  /Users/javi/Development/sandbox/reason-hello/src/a.re
  
  There's been an error running Reason's refmt parser on a file.
...
  Please file an issue on github.com/facebook/reason. Thanks!
  
ninja: error: rebuilding 'build.ninja': subcommand failed
...
```

Should we read the line, characters and error message from there? I can include it to the regexp.

> For warnings

I realized the regexp wasn't even looking for warnings 😅  but now they are covered (see [latest](https://github.com/freebroccolo/ocaml-language-server/pull/32/commits/4c810745a96c5e58609f4a12c917321b38c3a6d7) [commits](https://github.com/freebroccolo/ocaml-language-server/pull/32/commits/585f193ee6270e4cfb01977d55b800a8d92144bf)). It works pretty well!

image

> We might need to do some internal bookkeeping here.

Not sure you mean bookkeeping in Bucklescript or in the language server. I guess you mean the former, because from the lang server there's no way to know if there are no warnings because the code is ok or just because the warnings are being cached.

> Though we need to be careful not to show the UI lankily where bsb diagnosis supersede merlin's every few keystrokes.

I don't think this will be a problem, as bsb doesn't run on `fileChanged`, so there's no way for it to supersede merlin in that case (unless for hardcore users that save their files several times per second 😜 )

**Comment by chenglou** [comment]
> what other kinds of error output should we handle

These have line and col of -1 -1. I don't know them, so when we do show the line/col and some errors have absent line/col, we can just position the error to the beginning of the file

> Not sure you mean bookkeeping in Bucklescript or in the language server
I meant the latter, because if you keep warnings once and query bsb again (and assuming the file didn't change, which on second thought might be rare...) then you get no result back for this file; but you can't remove the previous warnings just yet. We can solve this later.

**Comment by let-def** [comment]
About Merlin, the main limitation is that Merlin doesn't know about your build process. The .merlin file tells some information about the build environment, but that's just an approximation.
Assuming the build environment is correct, Merlin should give the same results as OCaml.

Also Merlin works on a single file: it will assume that the dependencies are up to date and it won't check for interface inclusion. If you work on an implementation file, it won't report errors related to interface.

To summarize:
- if Merlin reports more errors than in your build, it is likely that Merlin has a different view of the project and that should be fixed (however, the normal build fails after first error, while Merlin can continue)
- if Merlin reports less errors, it is because of it's very local view and then the build becomes relevant.

Assuming a fine-grained setup, it should be worth checking build errors when Merlin reports no errors.
I am interested in feedback for tweaking merlin error reports :).

**Comment by jchavarri** [comment]
@freebroccolo afaik, from my side this is ready to be reviewed. I:

- Went through a list of bugs / glitches that I found out while using it this week, so more cases should be covered
- Checked some example files with [the list](https://github.com/BuckleScript/bucklescript/pull/1995/files) that @chenglou handed over to make sure those edge cases are covered too
- Added a setting `bsb.enabled` to `package.json` that defaults to `false`.

It depends on https://github.com/reasonml-editor/vscode-reasonml/pull/101 to work properly.

---

@let-def Thanks for the explanation. I'm probably the least indicated person to give feedback as I'm very new to OCaml / Reason :) but fwiw here are my thoughts from testing it this week:

The way it works at the moment is, if `bsb.enabled` is `false`, it just works as before. When it's `true`, Merlin keeps being the sole diagnostic tool being queried. But when there's a save or any other operation that requires a full sync, bsb is queried first and if there are no results, falls back to Merlin. This approach is of course adaptable, but I found it to have a good balance: Merlin gives the snappiness while editing, plus knowing the whole project is being compiled with bsb every time gives peace of mind.

> however, the normal build fails after first error, while Merlin can continue

I found the "show just one error per file at a time" approach from bsb to be quite nice: it helps focusing and spares brain cycles to think which error should be tackled next. But this is of course very personal :)

**Comment by bobzhang** [comment]
when will bsb get triggered? does ocaml-language-server accept push notification?

**Comment by freebroccolo** [comment]
@jchavarri I haven't had a chance to test this and still may not be able to until later in the week but I think it's probably okay to merge now. We can continue to tune and/or refactor as needed. Thanks again for working on this.

**Comment by freebroccolo** [comment]
> when will bsb get triggered? does ocaml-language-server accept push notification?

@bobzhang It looks like the way it is currently implemented, `bsb` will be triggered when there is a "full" document synchronization with the server. This happens when the file is **saved** and in a few other circumstances. This launches `bsb` as a new process and gathers the output.

It would not be hard to modify the server to listen for some sort of push notifications instead though if you have some ideas about how that should work.

**Comment by bobzhang** [comment]
`bsb` has an option `bsb -where` so that you can launch `bsb.exe` which should be loaded much quicker than then js wrapped version.
I am thinking of making `bsb` a daemon so that it can push build output to a named port, not sure how portable it is and if it fits with LTS protocol

**Comment by freebroccolo** [comment]
The language server itself communicates with the client/editor using JSON-RPC messages and it can be configured to do this over stdio, sockets, or node IPC. But currently the server isn’t setup to support multiple clients connecting to the same session, so trying to have `bsb` communicate with it that way is going to be complicated.

If you make `bsb` work like a daemon though and allow connections to a port or something like that, it shouldn’t be hard to modify the language server to be able to connect to it when a new session starts.

As long as it’s something you can easily connect to with node, portability shouldn’t be an issue on the language server side of things.

**Pull request merged**
