### PR TITLE
Add option to only run diagnostics on file save.

### PR DESCRIPTION
**Pull request by pittsw**
On large files, Merlin can take 30+ seconds to check for errors, which leads to situations where the user pauses while typing, triggering a long diagnostics check, and then finishes their line and hits save shortly after, which leads to a 29 second pause before the actual error check on the correct file contents can run.

### CODE REVIEW

**Comment by freebroccolo** [comment]
Thanks for the PR.

I agree that in cases where Merlin is taking too long this is a problem. However, unless I'm missing something, it doesn't seem like we really need special handling for this; can't the user just set a high value for `reason.debounce.linter` in their preferences? In fact, I think this is the reason I never got around to making a separate preference for diagnostics only on save.

It doesn't seem like you can use `Infinity` there, which would be ideal, but you can still set the delay to something like 1 hour (3600000) which should case the diagnostics to never trigger in practice while the user is editing, except on save.

Perhaps this should be made clearer in the documentation.

**Comment by freebroccolo** [comment]
Actually it looks like "Infinity" (with quotes) does work as expected although the preferences panel gives a warning about it being an incorrect type.

**Comment by freebroccolo** [comment]
I've updated the `vscode-reasonml` settings spec so that it no longer complains if "Infinity" is used instead of an integer.

**Comment by arxanas** [comment]
The string "Infinity" isn't a great value to indicate that in Atom. The reason is that Atom provides the ability to annotate config variables with types so that they're rendered more appropriately to the user for editing. It would be a shame if we had to change this config value to a string from an int and lose some sanity checks in the Atom configuration for this package. Maybe a value like 0 or -1 would be better to indicate infinity?

**Comment by freebroccolo** [comment]
The way it works now is that there are two types of values that are allowed for that setting, an integer or specifically the string "Infinity". This is enforced by the [JSON schema](http://json-schema.org/) spec for the settings, which you can see [here](https://github.com/reasonml-editor/vscode-reasonml/blob/master/package.json#L56-L68).

I was under the impression that Atom is also using JSON schema for the settings. Is that not the case?

**Comment by freebroccolo** [comment]
Just to be clear, the main reason I was suggesting for using "Infinity" is because it doesn't require any changes to the logic of the server. "Infinity" will be parsed as the JS number value `Infinity`. If we used something else, we wouldn't get that for free.

**Comment by freebroccolo** [comment]
Indeed, it looks like Atom is also using JSON schema based on [this](https://atom.io/docs/api/v1.22.1/Config).

**Comment by pittsw** [comment]
Okay, that would make sense too.  One issue we observed is that Nuclide wouldn't send the save event unless we used the rich value for `textDocumentSync` instead of just the enum, but I don't know enough about LSP internals to know if that's a problem with Nuclide or if that's working as expected.  Sounds like the VS Code plugin will always send save events?

**Comment by arxanas** [comment]
It doesn't seem to work in Nuclide to use `oneOf`, for some reason. This setting works:

```
      "debounceTime": {
        "title": "Testing debounce time config (ms)",
        "type": "integer",
        "default": 200
      },
```

and it renders an item in the config, but not this one:

```
      "debounceTime": {
        "title": "Testing debounce time config (ms)",
        "oneOf": [
          {"type": "integer"},
          {"enum": ["Infinity"]}
        ],
        "default": 200
      },
```

This could be an Atom- or Nuclide-specific issue, or it could be that Atom doesn't support a lot of the JSON schema, but I'm not sure which.

**Comment by freebroccolo** [comment]
> One issue we observed is that Nuclide wouldn't send the save event unless we used the rich value for textDocumentSync instead of just the enum, but I don't know enough about LSP internals to know if that's a problem with Nuclide or if that's working as expected. Sounds like the VS Code plugin will always send save events?

Hmm, I'm not sure what this is about. Certainly the vscode plugin currently seems to be working as expected with regard save events, etc., as far as I can tell.

However, if using the extended capability value for `textDocumentSync` really makes a difference for nuclide for some reason then I think it's okay to change it. Can we split that part out into a separate PR?

**Comment by pittsw** [comment]
After looking over the language protocol and talking internally, we think that Nuclide not sending `didSave` notifications unless this is set is actually a bug in Nuclide, so we'll just fix it there and use a long debounce :)

**Comment by freebroccolo** [comment]
> This could be an Atom- or Nuclide-specific issue, or it could be that Atom doesn't support a lot of the JSON schema, but I'm not sure which.

@arxanas I looked through the Atom config code and found [this](https://github.com/atom/atom/blob/v1.22.1/src/config.coffee#L1171-L1293). It would appear that they rolled their own validation system for some reason but it seems to only support basic types.

I'm guessing all of the other things like requiring unique items in arrays or min/max length are not checked either. One way you could test this one would be to try using the following setting and see if it complains if you using a value of `["merlin", "merlin"]`.


```
"reason.diagnostics.tools": {
  "type": "array",
  "items": {
    "enum": ["merlin", "bsb"]
  },
  "default": ["merlin"],
  "maxItems": 2,
  "uniqueItems": true,
  "description":
    "Specifies which tool or tools will be used to get diagnostics. If you choose both \"merlin\" and \"bsb\", merlin will be used while editing and bsb when saving."
}
```

Anyway, it's been awhile since I've used nuclide, but even if JSON schema support is incomplete in Atom, is this something you can address in nuclide? Do you have a separate UI for nuclide config settings where you could support more of this stuff?

**Comment by arxanas** [comment]
I'm 90% certain that the Nuclide configuration is implemented just in terms of the Atom configuration. To configure it you go to the package settings for Nuclide and find the subsection for the Nuclide package you want to configure.

**Pull request closed without merging**
