### PR TITLE
Ignore empty didChangeConfiguration messages (fixes #66)

### LINKED ISSUE #66: Crash on didChangeConfiguration with empty settings
The latest nvim language client is sending a 'workspace/didChangeConfiguration' with the settings parameter set to {}. This causes the server to crash:

```
/usr/lib/node_modules/ocaml-language-server/bin/server/processes/merlin.js:14
                if (this.session.settings.reason.diagnostics.merlinPerfLogging) {
                                                 ^

TypeError: Cannot read property 'diagnostics' of undefined
    at logMessage (/usr/lib/node_modules/ocaml-language-server/bin/server/processes/merlin.js:14:50)
    at /usr/lib/node_modules/ocaml-language-server/node_modules/lodash/lodash.js:5157:35
    at Interface._onLine (readline.js:280:5)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
```

See this issue for more details: https://github.com/autozimu/LanguageClient-neovim/issues/183

### PR DESCRIPTION
**Pull request by af**
These messages, sent from the current version of LanguageClient-neovim,
cause the server to crash on start.

This is probably a simplistic/naive fix, but the language server does work seamlessly for me with it (neovim 0.2.1, latest LanguageClient-neovim).

### CODE REVIEW

**Comment by freebroccolo** [comment]
Thanks for this pull request. I will hold off on merging this for the moment because I think the issue in question is actually fixed in another place in my local branch which is not yet pushed to `master`. I'll come back to this if not though.

**Comment by af** [comment]
No problem, worst case it might help a couple of people who (like myself) were struggling to get vim-language server integration running in the meantime

**Comment by freebroccolo** [comment]
I think this should be addressed in the latest released (via 4a175c17de2bd19f9d179e85563cb2fe8e864a4e). Please let me know if not.

**Comment by af** [comment]
Yep, latest release is working for me. Thanks!

**Pull request closed without merging**
